from django.urls import path
from .views import (
    UserListAPIView, UserDetailAPIView, CurrentUserView, ChangePasswordView, 
    RoleListCreateAPIView, RoleDetailAPIView,
    AdminChangeUserPasswordView, ProjectClientListCreateAPIView, ProjectClientDetailAPIView,
    ProjectBusinessAddressListCreateAPIView, ProjectBusinessAddressDetailAPIView,
    DomainOrServerThirdPartyServiceProviderListCreateAPIView, DomainOrServerThirdPartyServiceProviderDetailAPIView,
    ProjectDomainListCreateAPIView, ProjectDomainDetailAPIView,
    ProjectServerListCreateAPIView, ProjectServerDetailAPIView,
    ProjectFinanceListCreateAPIView, ProjectFinanceDetailAPIView,
    TeamListCreateAPIView, TeamDetailAPIView,
    ProjectTeamListCreateAPIView, ProjectTeamDetailAPIView,
    ProjectNatureListCreateAPIView, ProjectNatureDetailAPIView, ProjectExbotListCreateAPIView, ProjectExbotDetailAPIView,
    ProjectListCreateAPIView, ProjectDetailAPIView,
    ProjectSummaryListAPIView,
    ProjectBaseInformationListCreateAPIView, ProjectBaseInformationDetailAPIView,
    ProjectExcutionListCreateAPIView, ProjectExcutionDetailAPIView,
    ProjectTeamMemberListCreateAPIView, ProjectTeamMemberDetailAPIView,
    ProjectServiceListCreateAPIView, ProjectServiceDetailAPIView,
    EmployeeDailyActivityListCreateAPIView, EmployeeDailyActivityDetailAPIView,
    ActivityLogListCreateAPIView, ActivityLogDetailAPIView,
    InvoiceDetailAPIView, InvoicePDFView, ClientInvoiceListAPIView, InvoiceListCreateAPIView,
    InvoiceItemListCreateAPIView, InvoiceItemDetailAPIView,
    PaymentListCreateAPIView, PaymentDetailAPIView,
    InvoicePaymentListCreateAPIView, InvoicePaymentDetailAPIView,
    ActivityExceedCommentListCreateAPIView, ActivityExceedCommentDetailAPIView,
    NotificationListCreateAPIView, NotificationDetailAPIView,
    EmployeeLeaveListCreateAPIView, EmployeeLeaveDetailAPIView,
    CompanyListCreateAPIView, CompanyDetailAPIView,
    CompanyProfileListCreateAPIView, CompanyProfileDetailAPIView,
    SalaryListCreateAPIView, SalaryDetailAPIView, EmployeeSalarySummaryListAPIView,
    AttendanceListCreateAPIView, AttendanceDetailAPIView,
    EmployeeListCreateAPIView, EmployeeDetailAPIView,
    UserSalaryListCreateAPIView, UserSalaryDetailAPIView, SalaryIncrementListCreateAPIView, SalaryIncrementDetailAPIView,
    OtherIncomeListCreateAPIView, OtherIncomeDetailAPIView,
    OtherExpenseListCreateAPIView, OtherExpenseDetailAPIView,
    UserDesignationsAPIView,
    ProjectDocumentListCreateAPIView, ProjectDocumentDetailAPIView,
    ClientAdvanceListAPIView,
    ClientAdvanceDetailAPIView,
    ClientSummaryListAPIView,
    EmployeeSpecificActivityListAPIView,
    EmployeeWorkDetailsAPIView,
    EmployeePerformanceAPIView,
    TeamPerformanceAPIView,
    ApplyAdvanceCreditView,
    PermissionListAPIView,
    RoleCreateAPIView,
    UnreadNotificationCountAPIView,
    MarkAllNotificationsReadAPIView,
    LeadViewSet, FollowUpViewSet, LeadDashboardStatsAPIView,
    ScheduleListCreateAPIView, ScheduleDetailAPIView,
)

from .financial_views import (
    IncomeStatementView, CashFlowStatementView, BalanceSheetView, ProjectAnalyticalAPIView,
    ServerAnalyticsAPIView, DomainAnalyticsAPIView, ExbotAnalyticsAPIView
)

urlpatterns = [
    path('api/reports/income-statement/', IncomeStatementView.as_view(), name='api-income-statement'),
    path('api/reports/cash-flow/', CashFlowStatementView.as_view(), name='api-cash-flow'),
    path('api/reports/balance-sheet/', BalanceSheetView.as_view(), name='api-balance-sheet'),
    path('api/analytical/projects/', ProjectAnalyticalAPIView.as_view(), name='api-analytical-projects'),
    path('api/analytical/servers/', ServerAnalyticsAPIView.as_view(), name='api-analytical-servers'),
    path('api/analytical/domains/', DomainAnalyticsAPIView.as_view(), name='api-analytical-domains'),
    path('api/analytical/exbots/', ExbotAnalyticsAPIView.as_view(), name='api-analytical-exbots'),
    path('api/users/', UserListAPIView.as_view(), name='api-user-list'),
    path('api/users/<int:pk>/', UserDetailAPIView.as_view(), name='api-user-detail'),
    path('api/users/me/', CurrentUserView.as_view(), name='api-user-me'),
    path('api/users/designations/', UserDesignationsAPIView.as_view(), name='api-user-designations'),
    path('api/change-password/', ChangePasswordView.as_view(), name='api-change-password'),
    path('api/admin-change-password/<int:pk>/', AdminChangeUserPasswordView.as_view(), name='api-admin-change-password'),
    path('api/roles/', RoleListCreateAPIView.as_view(), name='api-role-list-create'),
    path('api/roles/<int:pk>/', RoleDetailAPIView.as_view(), name='api-role-detail'),
    path('api/project-clients/', ProjectClientListCreateAPIView.as_view(), name='api-project-client-list-create'),
    path('api/project-clients/<int:pk>/', ProjectClientDetailAPIView.as_view(), name='api-project-client-detail'),
    path('api/project-business-addresses/', ProjectBusinessAddressListCreateAPIView.as_view(), name='api-project-business-address-list-create'),
    path('api/project-business-addresses/summary/', ClientSummaryListAPIView.as_view(), name='api-client-summary-list'),
    path('api/project-business-addresses/<int:pk>/', ProjectBusinessAddressDetailAPIView.as_view(), name='api-project-business-address-detail'),
    path('api/domain-or-server-third-party-service-providers/', DomainOrServerThirdPartyServiceProviderListCreateAPIView.as_view(), name='api-domain-or-server-third-party-service-provider-list-create'),
    path('api/domain-or-server-third-party-service-providers/<int:pk>/', DomainOrServerThirdPartyServiceProviderDetailAPIView.as_view(), name='api-domain-or-server-third-party-service-provider-detail'),
    path('api/project-domains/', ProjectDomainListCreateAPIView.as_view(), name='api-project-domain-list-create'),
    path('api/project-domains/<int:pk>/', ProjectDomainDetailAPIView.as_view(), name='api-project-domain-detail'),
    path('api/project-servers/', ProjectServerListCreateAPIView.as_view(), name='api-project-server-list-create'),
    path('api/project-servers/<int:pk>/', ProjectServerDetailAPIView.as_view(), name='api-project-server-detail'),
    path('api/project-exbots/', ProjectExbotListCreateAPIView.as_view(), name='api-project-exbot-list-create'),
    path('api/project-exbots/<int:pk>/', ProjectExbotDetailAPIView.as_view(), name='api-project-exbot-detail'),
    path('api/project-finances/', ProjectFinanceListCreateAPIView.as_view(), name='api-project-finance-list-create'),
    path('api/project-finances/<int:pk>/', ProjectFinanceDetailAPIView.as_view(), name='api-project-finance-detail'),   
    path('api/teams/', TeamListCreateAPIView.as_view(), name='api-team-list-create'),
    path('api/teams/<int:pk>/', TeamDetailAPIView.as_view(), name='api-team-detail'),
    path('api/project-teams/', ProjectTeamListCreateAPIView.as_view(), name='api-project-team-list-create'),
    path('api/project-teams/<int:pk>/', ProjectTeamDetailAPIView.as_view(), name='api-project-team-detail'),
    path('api/project-natures/', ProjectNatureListCreateAPIView.as_view(), name='api-project-nature-list-create'),
    path('api/project-natures/<int:pk>/', ProjectNatureDetailAPIView.as_view(), name='api-project-nature-detail'),

    path('api/projects/', ProjectListCreateAPIView.as_view(), name='api-project-list-create'),
    path('api/projects/summary/', ProjectSummaryListAPIView.as_view(), name='api-project-summary-list'),
    path('api/projects/<int:pk>/', ProjectDetailAPIView.as_view(), name='api-project-detail'),
    path('api/project-base-information/', ProjectBaseInformationListCreateAPIView.as_view(), name='api-project-base-information-list-create'),
    path('api/project-base-information/<int:pk>/', ProjectBaseInformationDetailAPIView.as_view(), name='api-project-base-information-detail'),
    path('api/project-executions/', ProjectExcutionListCreateAPIView.as_view(), name='api-project-execution-list-create'),
    path('api/project-executions/<int:pk>/', ProjectExcutionDetailAPIView.as_view(), name='api-project-execution-detail'),
    path('api/project-team-members/', ProjectTeamMemberListCreateAPIView.as_view(), name='api-project-team-member-list-create'),
    path('api/project-team-members/<int:pk>/', ProjectTeamMemberDetailAPIView.as_view(), name='api-project-team-member-detail'),
    path('api/project-services/', ProjectServiceListCreateAPIView.as_view(), name='api-project-service-list-create'),
    path('api/project-services/<int:pk>/', ProjectServiceDetailAPIView.as_view(), name='api-project-service-detail'),
    path('api/employee-daily-activities/', EmployeeDailyActivityListCreateAPIView.as_view(), name='api-employee-daily-activity-list-create'),
    path('api/employees/<int:employee_id>/activities/', EmployeeSpecificActivityListAPIView.as_view(), name='api-employee-activities'),
    path('api/employees/<int:employee_id>/work-details/', EmployeeWorkDetailsAPIView.as_view(), name='api-employee-work-details'),
    path('api/employee-daily-activities/<int:pk>/', EmployeeDailyActivityDetailAPIView.as_view(), name='api-employee-daily-activity-detail'),
    path('api/activity-logs/', ActivityLogListCreateAPIView.as_view(), name='api-activity-log-list-create'),
    path('api/activity-logs/<int:pk>/', ActivityLogDetailAPIView.as_view(), name='api-activity-log-detail'),
    path('api/invoices/', InvoiceListCreateAPIView.as_view(), name='api-invoice-list-create'),
    path('api/project-business-addresses/<int:client_id>/invoices/', ClientInvoiceListAPIView.as_view(), name='api-client-invoice-list'),
    path('api/project-business-addresses/<int:client_id>/invoices/<int:pk>/', InvoiceDetailAPIView.as_view(), name='api-invoice-detail'),
    path('api/project-business-addresses/<int:client_id>/invoices/<int:pk>/pdf/', InvoicePDFView.as_view(), name='api-invoice-pdf'),
    path('api/project-business-addresses/<int:client_id>/invoices/<int:pk>/payments/', InvoicePaymentListCreateAPIView.as_view(), name='api-invoice-payment-list-create'),
    path('api/project-business-addresses/<int:client_id>/invoices/<int:invoice_pk>/payments/<int:pk>/', InvoicePaymentDetailAPIView.as_view(), name='api-invoice-payment-detail'),
    path('api/project-business-addresses/<int:client_id>/advances/', ClientAdvanceListAPIView.as_view(), name='api-client-advance-list'),
    path('api/project-business-addresses/<int:client_id>/advances/<int:pk>/', ClientAdvanceDetailAPIView.as_view(), name='api-client-advance-detail'),
    path('api/invoice-items/', InvoiceItemListCreateAPIView.as_view(), name='api-invoice-item-list-create'),
    path('api/invoice-items/<int:pk>/', InvoiceItemDetailAPIView.as_view(), name='api-invoice-item-detail'),
    path('api/payments/', PaymentListCreateAPIView.as_view(), name='api-payment-list-create'),
    path('api/payments/<int:pk>/', PaymentDetailAPIView.as_view(), name='api-payment-detail'),
    path('api/activity-exceed-comments/', ActivityExceedCommentListCreateAPIView.as_view(), name='api-activity-exceed-comment-list-create'),
    path('api/activity-exceed-comments/<int:pk>/', ActivityExceedCommentDetailAPIView.as_view(), name='api-activity-exceed-comment-detail'),
    path('api/notifications/', NotificationListCreateAPIView.as_view(), name='api-notification-list-create'),
    path('api/notifications/unread-count/', UnreadNotificationCountAPIView.as_view(), name='api-notification-unread-count'),
    path('api/notifications/mark-all-read/', MarkAllNotificationsReadAPIView.as_view(), name='api-notification-mark-all-read'),
    path('api/notifications/<int:pk>/', NotificationDetailAPIView.as_view(), name='api-notification-detail'),
    path('api/employee-leaves/', EmployeeLeaveListCreateAPIView.as_view(), name='api-employee-leave-list-create'),
    path('api/employee-leaves/<int:pk>/', EmployeeLeaveDetailAPIView.as_view(), name='api-employee-leave-detail'),
    path('api/companies/', CompanyListCreateAPIView.as_view(), name='api-company-list-create'),
    path('api/companies/<int:pk>/', CompanyDetailAPIView.as_view(), name='api-company-detail'),
    path('api/company-profiles/', CompanyProfileListCreateAPIView.as_view(), name='api-company-profile-list-create'),
    path('api/company-profiles/<int:pk>/', CompanyProfileDetailAPIView.as_view(), name='api-company-profile-detail'),
    path('api/salaries/', SalaryListCreateAPIView.as_view(), name='api-salary-list-create'),
    path('api/salaries/summary/', EmployeeSalarySummaryListAPIView.as_view(), name='api-salary-summary-list'),
    path('api/salaries/<int:pk>/', SalaryDetailAPIView.as_view(), name='api-salary-detail'),
    path('api/attendance/', AttendanceListCreateAPIView.as_view(), name='api-attendance-list-create'),
    path('api/attendance/<int:pk>/', AttendanceDetailAPIView.as_view(), name='api-attendance-detail'),
    path('api/employees/', EmployeeListCreateAPIView.as_view(), name='api-employee-list-create'),
    path('api/employees/<int:pk>/', EmployeeDetailAPIView.as_view(), name='api-employee-detail'),
    path('api/user-salaries/', UserSalaryListCreateAPIView.as_view(), name='api-user-salary-list-create'),
    path('api/user-salaries/<int:pk>/', UserSalaryDetailAPIView.as_view(), name='api-user-salary-detail'),
    path('api/salary-increments/', SalaryIncrementListCreateAPIView.as_view(), name='api-salary-increment-list-create'),
    path('api/salary-increments/<int:pk>/', SalaryIncrementDetailAPIView.as_view(), name='api-salary-increment-detail'),
    path('api/other-incomes/', OtherIncomeListCreateAPIView.as_view(), name='api-other-income-list-create'),

    path('api/other-incomes/<int:pk>/', OtherIncomeDetailAPIView.as_view(), name='api-other-income-detail'),
    path('api/other-expenses/', OtherExpenseListCreateAPIView.as_view(), name='api-other-expense-list-create'),
    path('api/other-expenses/<int:pk>/', OtherExpenseDetailAPIView.as_view(), name='api-other-expense-detail'),
    path('api/permissions/', PermissionListAPIView.as_view(), name='api-permission-list'),
    path('api/roles/create/', RoleCreateAPIView.as_view(), name='api-role-create'),
    path('api/project-documents/', ProjectDocumentListCreateAPIView.as_view(), name='api-project-document-list-create'),
    path('api/project-documents/<int:pk>/', ProjectDocumentDetailAPIView.as_view(), name='api-project-document-detail'),
    path('api/employee-performance/', EmployeePerformanceAPIView.as_view(), name='api-employee-performance'),
    path('api/team-performance/', TeamPerformanceAPIView.as_view(), name='api-team-performance'),
    path('api/project-business-addresses/<int:client_id>/invoices/<int:pk>/apply-advance/', ApplyAdvanceCreditView.as_view(), name='api-apply-advance-credit'),
    path('api/leads/dashboard/', LeadDashboardStatsAPIView.as_view(), name='api-lead-dashboard'),
    path('api/leads/', LeadViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-lead-list-create'),
    path('api/leads/<int:pk>/', LeadViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-lead-detail'),
    path('api/followups/', FollowUpViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-followup-list-create'),
    path('api/followups/<int:pk>/', FollowUpViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-followup-detail'),
    path('api/schedules/', ScheduleListCreateAPIView.as_view(), name='api-schedule-list-create'),
    path('api/schedules/<int:pk>/', ScheduleDetailAPIView.as_view(), name='api-schedule-detail'),
]
