# Generated by Django 6.0.2 on 2026-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0078_invoiceitem_project_exbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdomain',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
        migrations.AddField(
            model_name='projectexbot',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
        migrations.AddField(
            model_name='projectserver',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
    ]
