# Generated by Django 6.0.2 on 2026-04-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0079_projectdomain_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
    ]
