# Generated by Django 5.2.5 on 2026-05-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0080_projectservice_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='project_finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='djangosimplemissionapp.projectfinance'),
        ),
        migrations.AddField(
            model_name='projectfinance',
            name='invoice_status',
            field=models.CharField(choices=[('NOT_INVOICED', 'Not Invoiced'), ('INVOICED', 'Invoiced')], default='NOT_INVOICED', max_length=20),
        ),
    ]
