# Generated by Django 5.2.5 on 2026-05-02 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0082_user_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('nature_of_business', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=255)),
                ('contacted_date', models.DateField(blank=True, null=True)),
                ('service_required', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('interest_level', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('follow_up', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('denied', 'Denied')], default='new', max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('lead_source', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lead_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('followup_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='djangosimplemissionapp.lead')),
            ],
        ),
    ]
