# Generated by Django 6.0.2 on 2026-05-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0083_lead_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_employee_performance', 'Can view all employee performance'), ('view_own_employee_performance', 'Can view own employee performance'), ('view_all_leads', 'Can view all leads'), ('view_own_leads', 'Can view own leads')]},
        ),
    ]
