# Generated by Django 5.2.5 on 2026-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0084_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
