# Generated by Django 5.2.5 on 2026-05-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0085_lead_address_lead_email_lead_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='conversion_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='interest_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
