# Generated by Django 5.2.5 on 2026-05-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0086_followup_conversion_status_followup_interest_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='conversion_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_followup_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='remark',
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
