# Generated by Django 6.0.2 on 2026-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0088_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
