# Generated by Django 6.0.2 on 2026-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0090_schedule_created_by_alter_schedule_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('denied', 'Denied')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest_level',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
