# Generated by Django 6.0.2 on 2026-05-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0091_lead_conversion_status_lead_follow_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='conversion_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_followup_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='remark',
        ),
    ]
