# Generated by Django 6.0.2 on 2026-05-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0092_remove_lead_conversion_status_remove_lead_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='interaction_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('meeting', 'Direct Meeting'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], default='call', max_length=20),
        ),
    ]
