# Generated by Django 6.0.2 on 2026-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0094_followup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='service_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
