# Generated by Django 6.0.2 on 2026-05-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0095_alter_lead_service_required'),
        ('djangosimplemissionapp', '0095_followup_interaction_date'),
    ]

    operations = [
    ]
