# Generated by Django 6.0.2 on 2026-05-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0096_merge_20260507_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_schedules', to='djangosimplemissionapp.role'),
        ),
    ]
