# Generated by Django 6.0.2 on 2026-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0097_alter_followup_options_schedule_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_project_created',
            field=models.BooleanField(default=False),
        ),
    ]
