# Generated by Django 6.0.2 on 2026-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0098_followup_is_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
