# Generated by Django 6.0.2 on 2026-05-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0099_alter_lead_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_role', to='djangosimplemissionapp.role'),
        ),
    ]
