# Generated by Django 6.0.2 on 2026-05-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0100_lead_assigned_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexbot',
            options={'permissions': [('view_exbot_stats', 'Can view exbot analytics and stats')]},
        ),
    ]
