# Generated by Django 6.0.2 on 2026-05-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0101_alter_projectexbot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('view_server_notifications', 'Can view server related notifications'), ('view_domain_notifications', 'Can view domain related notifications'), ('view_exbot_notifications', 'Can view exbot related notifications')]},
        ),
    ]
