# Generated by Django 5.2.5 on 2026-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0102_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinance',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20),
        ),
    ]
