# Generated by Django 5.2.5 on 2026-05-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0103_projectfinance_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinance',
            name='manpower_cost',
        ),
        migrations.RemoveField(
            model_name='projectfinance',
            name='total_balance_due',
        ),
        migrations.RemoveField(
            model_name='projectfinance',
            name='total_invoiced',
        ),
        migrations.RemoveField(
            model_name='projectfinance',
            name='total_paid',
        ),
    ]
