# Generated by Django 5.2.5 on 2026-05-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0104_remove_projectfinance_manpower_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ['-start_date'], 'permissions': [('view_all_leaves', 'Can view all employee leaves'), ('approve_leave', 'Can approve employee leave'), ('reject_leave', 'Can reject employee leave')]},
        ),
    ]
