# Generated by Django 5.2.5 on 2026-05-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0105_alter_employeeleave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ['-start_date'], 'permissions': [('viewall_employeeleave', 'Can view all employee leaves'), ('approve_employeeleave', 'Can approve employee leave'), ('reject_employeeleave', 'Can reject employee leave')]},
        ),
    ]
