# Generated by Django 5.2.5 on 2026-05-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0106_alter_employeeleave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_teamperformance', 'Can view team performance analytics'), ('view_all_team_performance', 'Can view performance of all teams'), ('view_own_team_performance', 'Can view performance of own team only'), ('viewown_team', 'Can view own team details '), ('viewall_team', 'Can view all team details')]},
        ),
    ]
