# Generated by Django 5.2.5 on 2026-05-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0107_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_employee_performance', 'Can view all employee performance'), ('view_own_employee_performance', 'Can view own employee performance'), ('view_all_leads', 'Can view all leads'), ('view_own_leads', 'Can view own leads'), ('viewall_user', 'Can view all user details'), ('viewown_user', 'Can view own user details')]},
        ),
    ]
