# Generated by Django 5.2.5 on 2026-06-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0108_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicemember',
            options={'permissions': [('view_all_projectservicemembers', 'Can view all project service members'), ('view_own_projectservicemembers', 'Can view own project service member assignments')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('view_all_projectteammembers', 'Can view all project team members'), ('view_own_projectteammembers', 'Can view own project team member assignments')]},
        ),
    ]
