# Generated by Django 5.2.5 on 2026-06-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0109_add_projectteammember_servicemember_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicemember',
            options={'permissions': [('viewall_projectservicemembers', 'Can view all project service members'), ('viewown_projectservicemembers', 'Can view own project service member assignments')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('viewall_projectteammembers', 'Can view all project team members'), ('viewown_projectteammembers', 'Can view own project team member assignments')]},
        ),
    ]
