# Generated by Django 5.2.5 on 2026-06-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0110_alter_projectservicemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicemember',
            options={'permissions': [('all_projectservicemembers', 'Can view all project service members'), ('own_projectservicemembers', 'Can view own project service member assignments')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('all_projectteammembers', 'Can view all project team members'), ('own_projectteammembers', 'Can view own project team member assignments')]},
        ),
    ]
