# Generated by Django 5.2.5 on 2026-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0111_alter_projectservicemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicemember',
            options={'permissions': [('all_projectservicemember', 'Can view all project service members'), ('own_projectservicemember', 'Can view own project service member assignments')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('all_projectteammember', 'Can view all project team members'), ('own_projectteammember', 'Can view own project team member assignments')]},
        ),
        migrations.AddField(
            model_name='projectservicemember',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
    ]
