# Generated by Django 5.2.5 on 2026-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0112_alter_projectservicemember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectservicemember',
            name='b',
        ),
        migrations.RemoveField(
            model_name='projectteammember',
            name='b',
        ),
    ]
