# Generated by Django 5.2.5 on 2026-06-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0114_systemauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view domain analytics and stats'), ('viewnameonly_projectdomain', 'can view '), ('viewprovider_projectdomain', 'can view '), ('viewpurshed_projectdomain', 'can view ')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view server analytics and stats'), ('viewnameonly_projectserver', 'can view '), ('viewprovider_projectserver', 'can view '), ('viewtype_projectserver', 'can view '), ('viewpurshedfrom_projectserver', 'can view ')]},
        ),
    ]
