# Generated by Django 5.2.5 on 2026-06-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0115_alter_projectdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view domain analytics and stats'), ('viewnameonly_projectdomain', 'can view ')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view server analytics and stats'), ('viewnameonly_projectserver', 'can view ')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('all_projectteammember', 'Can view all project team members'), ('own_projectteammember', 'Can view own project team member assignments'), ('viewnameonly_projectteammember', 'Can view name and dates only for project team members')]},
        ),
    ]
