# Generated by Django 5.2.5 on 2026-06-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0116_alter_projectdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('all_projectteammember', 'Can view all project team members'), ('own_projectteammember', 'Can view own project team member assignments')]},
        ),
    ]
