# Generated by Django 5.2.5 on 2026-06-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0117_alter_projectteammember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservicemember',
            options={'permissions': [('all_projectservicemember', 'Can view all project service members'), ('own_projectservicemember', 'Can view own project service member assignments'), ('alldate_projectservicemember', 'Can view all project service member dates')]},
        ),
        migrations.AlterModelOptions(
            name='projectteammember',
            options={'permissions': [('all_projectteammember', 'Can view all project team members'), ('own_projectteammember', 'Can view own project team member assignments'), ('alldate_projectteammember', 'Can view all project team member dates')]},
        ),
    ]
