# Generated by Django 5.2.5 on 2026-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0118_alter_projectservicemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'permissions': [('approve_attendance', 'Can approve attendance'), ('reject_attendance', 'Can reject attendance')]},
        ),
        migrations.AddField(
            model_name='attendance',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
