# Generated by Django 5.2.5 on 2026-06-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0119_alter_attendance_options_attendance_approval_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view domain analytics and stats'), ('viewnameonly_projectdomain', 'can view '), ('view_financials_projectdomain', 'Can view financial data of domains'), ('view_dates_projectdomain', 'Can view purchase/expiry dates of domains')]},
        ),
        migrations.AlterModelOptions(
            name='projectexbot',
            options={'permissions': [('view_exbot_stats', 'Can view exbot analytics and stats'), ('view_financials_projectexbot', 'Can view financial data of exbots'), ('view_dates_projectexbot', 'Can view active/deactive dates of exbots')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view server analytics and stats'), ('viewnameonly_projectserver', 'can view '), ('view_financials_projectserver', 'Can view financial data of servers'), ('view_dates_projectserver', 'Can view purchase/expiry dates of servers')]},
        ),
    ]
