# Generated by Django 5.2.5 on 2026-06-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0120_alter_projectdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view domain analytics and stats'), ('viewnameonly_projectdomain', 'can view '), ('viewfinancials_projectdomain', 'Can view financial data of domains'), ('viewdates_projectdomain', 'Can view purchase/expiry dates of domains')]},
        ),
        migrations.AlterModelOptions(
            name='projectexbot',
            options={'permissions': [('view_exbot_stats', 'Can view exbot analytics and stats'), ('viewfinancials_projectexbot', 'Can view financial data of exbots'), ('viewdates_projectexbot', 'Can view active/deactive dates of exbots')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view server analytics and stats'), ('viewnameonly_projectserver', 'can view '), ('viewfinancials_projectserver', 'Can view financial data of servers'), ('viewdates_projectserver', 'Can view purchase/expiry dates of servers')]},
        ),
    ]
