# Generated by Django 5.2.5 on 2026-06-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0121_alter_projectdomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard'), ('view_projectstats', 'Can view project analytics and stats'), ('view_financials_project', 'Can view financial data of projects')]},
        ),
    ]
