# Generated by Django 5.2.5 on 2026-06-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0122_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard'), ('view_projectstats', 'Can view project analytics and stats')]},
        ),
    ]
