# Generated by Django 5.2.5 on 2026-06-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0123_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard'), ('view_projectstats', 'Can view project analytics and stats'), ('view_projectfinancestats', 'Can view financial data of projects')]},
        ),
    ]
