# Generated by Django 5.2.5 on 2026-06-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0125_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedailyactivity',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('view_all_activities', 'Can view all employee daily activities'), ('view_own_activities', 'Can view own daily activities'), ('view_meandmyallprojecteammember_and_serviceteammember', 'Can view activities of self, project team members, and service team members')], 'verbose_name_plural': 'Employee Daily Activities'},
        ),
    ]
