# Generated by Django 5.2.5 on 2026-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0130_alter_employeedailyactivity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], default='Full Day', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
