# Generated by Django 5.2.5 on 2026-06-06 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0131_employeeleave_end_time_employeeleave_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersalary',
            options={'ordering': ['-effective_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='usersalary',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_salaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
