# Generated by Django 5.2.5 on 2026-06-06 10:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0132_alter_usersalary_options_usersalary_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Once locked, payroll cannot be modified. Lock after payment.'),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_salary', models.DecimalField(decimal_places=2, help_text='Salary before increment', max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, help_text='Amount of salary increase/decrease', max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, help_text='Salary after increment', max_digits=10)),
                ('effective_date', models.DateField()),
                ('remarks', models.TextField(blank=True, help_text='Reason for increment (e.g., Annual appraisal, promotion)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_increments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
