# Generated by Django 5.2.5 on 2026-06-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0133_salary_gross_salary_salary_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'permissions': [('approve_attendance', 'Can approve attendance'), ('reject_attendance', 'Can reject attendance'), ('viewall_attendance', 'Can view all attendance records'), ('viewown_attendance', 'Can view own attendance records')]},
        ),
    ]
