# Generated by Django 5.2.5 on 2026-06-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0134_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'permissions': [('view_all_salary', 'Can view all salary records'), ('view_own_salary', 'Can view own salary records')]},
        ),
        migrations.AlterModelOptions(
            name='salaryincrement',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('view_all_salarylincrement', 'Can view all salary increment records'), ('view_own_salarylincrement', 'Can view own salary increment records')]},
        ),
        migrations.AlterModelOptions(
            name='usersalary',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('view_all_usersalary', 'Can view all user salary records'), ('view_own_usersalary', 'Can view own user salary records')]},
        ),
    ]
