# Generated by Django 5.2.5 on 2026-06-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0135_alter_salary_options_alter_salaryincrement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'permissions': [('viewall_salary', 'Can view all salary records'), ('viewown_salary', 'Can view own salary records')]},
        ),
        migrations.AlterModelOptions(
            name='salaryincrement',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('viewall_salarylincrement', 'Can view all salary increment records'), ('viewown_salarylincrement', 'Can view own salary increment records')]},
        ),
        migrations.AlterModelOptions(
            name='usersalary',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('viewall_usersalary', 'Can view all user salary records'), ('viewown_usersalary', 'Can view own user salary records')]},
        ),
    ]
