# Generated by Django 5.2.5 on 2026-06-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0136_alter_salary_options_alter_salaryincrement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryincrement',
            options={'ordering': ['-effective_date', '-created_at'], 'permissions': [('viewall_salaryincrement', 'Can view all salary increment records'), ('viewown_salaryincrement', 'Can view own salary increment records')]},
        ),
    ]
