# Generated by Django 5.2.5 on 2026-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0137_alter_salaryincrement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectservicemember',
            name='role',
            field=models.CharField(choices=[('Service Manager', 'Service Manager'), ('Integration Developer', 'Integration Developer'), ('Developer', 'Developer'), ('Quality Assurance', 'Quality Assurance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='role',
            field=models.CharField(blank=True, choices=[('Project Manager', 'Project Manager'), ('Tech Lead', 'Tech Lead'), ('Tech Lead / Backend Developer', 'Tech Lead / Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('full stack', 'full stack'), ('Quality Assurance', 'Quality Assurance'), ('DevOps Engineer', 'DevOps Engineer'), ('Business Analyst', 'Business Analyst')], max_length=100, null=True),
        ),
    ]
