# Generated by Django 5.2.5 on 2026-06-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0138_alter_projectservicemember_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedailyactivity',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('view_all_activities', 'Can view all employee daily activities'), ('view_own_activities', 'Can view own daily activities'), ('viewmeandprojectmember_employeedailyactivity', 'Can view activities of self, project team members, and service team members'), ('viewmanagerallteammember_employeedailyactivity', 'Can view all team members including managers')], 'verbose_name_plural': 'Employee Daily Activities'},
        ),
    ]
