# Generated by Django 5.2.5 on 2026-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0139_alter_employeedailyactivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectservicemember',
            name='role',
            field=models.CharField(choices=[('Service Manager', 'Service Manager'), ('Project Manager', 'Project Manager'), ('Tech Lead', 'Tech Lead'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Mobile Developer', 'Mobile Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('QA Engineer', 'QA Engineer'), ('Quality Assurance', 'Quality Assurance'), ('Business Analyst', 'Business Analyst'), ('Solution Architect', 'Solution Architect'), ('Integration Developer', 'Integration Developer'), ('Developer', 'Developer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projectteammember',
            name='role',
            field=models.CharField(blank=True, choices=[('Project Manager', 'Project Manager'), ('Tech Lead', 'Tech Lead'), ('Tech Lead / Backend Developer', 'Tech Lead / Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Mobile Developer', 'Mobile Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('QA Engineer', 'QA Engineer'), ('Quality Assurance', 'Quality Assurance'), ('Business Analyst', 'Business Analyst'), ('Solution Architect', 'Solution Architect'), ('full stack', 'full stack')], max_length=100, null=True),
        ),
    ]
