# Generated by Django 5.2.5 on 2026-06-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0140_alter_projectservicemember_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'permissions': [('approve_attendance', 'Can approve attendance'), ('reject_attendance', 'Can reject attendance'), ('viewall_attendance', 'Can view all attendance records'), ('viewown_attendance', 'Can view own attendance records'), ('checkinedit_attendance', 'can edit checkin attendance')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_analytics', 'Can view analytical dashboard'), ('view_projectstats', 'Can view own project analytics and stats'), ('viewprojectfinancestats_analytics', 'Can view financial data of projects'), ('viewall_projectstats', 'can view all project analytics and stats')]},
        ),
        migrations.AlterModelOptions(
            name='projectdomain',
            options={'permissions': [('view_domain_stats', 'Can view own domain analytics and stats'), ('viewnameonly_projectdomain', 'can view '), ('viewfinancials_projectdomain', 'Can view financial data of domains'), ('viewdates_projectdomain', 'Can view purchase/expiry dates of domains'), ('viewall_domain_stats', 'can view all domain and stats')]},
        ),
        migrations.AlterModelOptions(
            name='projectexbot',
            options={'permissions': [('view_exbot_stats', 'Can view own exbot analytics and stats'), ('viewfinancials_projectexbot', 'Can view financial data of exbots'), ('viewdates_projectexbot', 'Can view active/deactive dates of exbots'), ('viewall_exbot_stats', 'Can view all exbot analytics and stats')]},
        ),
        migrations.AlterModelOptions(
            name='projectserver',
            options={'permissions': [('view_server_stats', 'Can view own server analytics and stats'), ('viewnameonly_projectserver', 'can view '), ('viewfinancials_projectserver', 'Can view financial data of servers'), ('viewdates_projectserver', 'Can view purchase/expiry dates of servers'), ('viewall_server_stats', 'Can view all server analytics and stats')]},
        ),
    ]
