# Generated by Django 5.2.5 on 2026-06-12 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0141_alter_attendance_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text="User's IP address during login")),
                ('device_name', models.CharField(blank=True, help_text="Device name (e.g., 'iPhone 12', 'Windows 10')", max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop'), ('Other', 'Other')], default='Desktop', help_text='Type of device used to login', max_length=50)),
                ('browser_name', models.CharField(blank=True, help_text="Browser name (e.g., 'Chrome', 'Safari')", max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, help_text='Browser version', max_length=50, null=True)),
                ('os_name', models.CharField(blank=True, help_text="Operating System (e.g., 'Windows', 'iOS')", max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, help_text='OS version', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent string', null=True)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='SUCCESS', max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, help_text='Time user logged out', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Time spent in session', null=True)),
                ('country', models.CharField(blank=True, help_text='Country inferred from IP', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City inferred from IP', max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Geographic latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Geographic longitude', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (e.g., reason for failed login)', null=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flag for suspicious login attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login Detail',
                'verbose_name_plural': 'User Login Details',
                'ordering': ['-login_time'],
                'permissions': [('view_all_logins', 'Can view all user login details'), ('view_own_logins', 'Can view own login details'), ('view_suspicious_logins', 'Can view suspicious login attempts')],
                'indexes': [models.Index(fields=['-login_time'], name='djangosimpl_login_t_560883_idx'), models.Index(fields=['user', '-login_time'], name='djangosimpl_user_id_e06450_idx'), models.Index(fields=['ip_address'], name='djangosimpl_ip_addr_312a52_idx'), models.Index(fields=['is_suspicious'], name='djangosimpl_is_susp_88d3a8_idx')],
            },
        ),
    ]
