# Generated by Django 5.2.5 on 2026-06-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0142_loginuserdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuserdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loginuserdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='loginuserdetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='loginuserdetails',
            name='longitude',
        ),
    ]
