# Generated by Django 5.2.5 on 2026-06-13 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0143_remove_loginuserdetails_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="User-friendly device name (e.g., 'My MacBook')", max_length=255)),
                ('device_id', models.CharField(help_text='Unique device identifier (MAC address, hardware ID, etc.)', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=50)),
                ('is_approved', models.BooleanField(default=False, help_text='Is this device approved for login?')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When was this device approved?', null=True)),
                ('approval_reason', models.TextField(blank=True, help_text='Reason for approval/rejection', null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Additional device information (OS, browser, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_devices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'permissions': [('manage_device_approvals', 'Can approve/reject user devices'), ('view_all_devices', 'Can view all user devices')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
