# Generated by Django 5.2.5 on 2026-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosimplemissionapp', '0144_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Unique device identifier (MAC address, hardware ID, etc.)', max_length=255),
        ),
    ]
